In [1]:
import os
import re
import shutil
import pandas as pd

In [2]:
absulte_path = os.path.abspath('.')
print(absulte_path)

e:\DSGP

In [3]:
data_set_path='data/raw'

In [4]:
import yaml
from pathlib import Path

# 1. Define Paths
base_path = Path(r".\data\raw\data set 4")
yaml_path = base_path / "data.yaml"
output_root = base_path / "reconstructed_dataset"

# 2. Load Class Names from YAML
with open(yaml_path, 'r') as f:
    data_cfg = yaml.safe_load(f)
class_names = data_cfg['names']

# 3. Define the splits shown in your image
splits = ['train', 'test', 'valid']

for split in splits:
    print(f"Processing {split} split...")
    image_dir = base_path / split / "images"
    label_dir = base_path / split / "labels"
    
    # Check if paths exist for this split
    if not image_dir.exists() or not label_dir.exists():
        continue

    for label_file in label_dir.glob("*.txt"):
        # Read the class ID (first number in the text file)
        with open(label_file, 'r') as f:
            content = f.readline().strip().split()
            if not content: continue
            class_id = int(content[0])
            class_name = class_names[class_id]

        # Create destination folder: reconstructed_dataset/train/Healthy/
        dest_folder = output_root / split / class_name
        dest_folder.mkdir(parents=True, exist_ok=True)

        # Find and copy the image
        img_found = False
        for ext in ['.jpg', '.jpeg', '.png']:
            img_path = image_dir / f"{label_file.stem}{ext}"
            if img_path.exists():
                shutil.copy(img_path, dest_folder / img_path.name)
                img_found = True
                break

Processing train split...
Processing test split...
Processing valid split...

In [5]:
folders=[]
error_count=0

for folder in ['Algal Leaf Spot (Cephaleuros parasiticus)',
               'Brown Blight (Colletotrichum camelliae)',
               'Gray Blight (Pestalotiopsis theae)',
               'Healthy',
               'Helopeltis (Helopeltis theivora)',
               'Red Leaf Spot (Phoma theicola)']:
    os.makedirs(os.path.join(absulte_path,data_set_path,'Data set 4','reconstructed_dataset',folder), exist_ok=True)
with os.scandir(os.path.join(absulte_path,data_set_path,'Data set 4','reconstructed_dataset')) as entries:
    for entry in entries:
        if entry.name not in ['test','train','valid']:
            continue
        if entry.is_dir():
            folders.append(entry.name)

            with os.scandir(os.path.join(absulte_path,data_set_path,'Data set 4','reconstructed_dataset',entry.name)) as folder_entries:
                for folder_entry in folder_entries:
                    match folder_entry.name:
                        case 'Algal Leaf Spot':
                            folder="Algal Leaf Spot (Cephaleuros parasiticus)"
                        case "Brown Blight":
                            folder="Brown Blight (Colletotrichum camelliae)"
                        case "Gray Blight":
                            folder="Gray Blight (Pestalotiopsis theae)"
                        case "Healthy":
                            folder="Healthy"
                        case "Helopeltis":
                            folder="Helopeltis (Helopeltis theivora)"
                        case "Red Leaf Spot":
                            folder="Red Leaf Spot (Phoma theicola)"
                        case _:
                            error_count+=1
                            continue

                    shutil.copytree(os.path.join(absulte_path,data_set_path,'Data set 4','reconstructed_dataset',entry.name,folder_entry.name),
                                  os.path.join(absulte_path,data_set_path,'Data set 4','reconstructed_dataset',folder),
                                  dirs_exist_ok=True)
                    print(os.path.join(absulte_path,data_set_path,'Data set 4','reconstructed_dataset',folder))
                    print(folder_entry.name)

folders

e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Algal Leaf Spot (Cephaleuros parasiticus)
Algal Leaf Spot
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Brown Blight (Colletotrichum camelliae)
Brown Blight
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Gray Blight (Pestalotiopsis theae)
Gray Blight
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Healthy
Healthy
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Helopeltis (Helopeltis theivora)
Helopeltis
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Red Leaf Spot (Phoma theicola)
Red Leaf Spot
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Algal Leaf Spot (Cephaleuros parasiticus)
Algal Leaf Spot
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Brown Blight (Colletotrichum camelliae)
Brown Blight
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Gray Blight (Pestalotiopsis theae)
Gray Blight
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Healthy
Healthy
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Helopeltis (Helopeltis theivora)
Helopeltis
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Red Leaf Spot (Phoma theicola)
Red Leaf Spot
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Algal Leaf Spot (Cephaleuros parasiticus)
Algal Leaf Spot
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Brown Blight (Colletotrichum camelliae)
Brown Blight
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Gray Blight (Pestalotiopsis theae)
Gray Blight
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Healthy
Healthy
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Helopeltis (Helopeltis theivora)
Helopeltis
e:\DSGP\data/raw\Data set 4\reconstructed_dataset\Red Leaf Spot (Phoma theicola)
Red Leaf Spot

['test', 'train', 'valid']

In [6]:
data_set_path='data/raw'
folders=[]
data=[]

#listing all folders in data set 3
with os.scandir(os.path.join(absulte_path,data_set_path,'Data set 3')) as entries:
    for entry in entries:
        if entry.name not in ['test','train','valid']:
            continue
        if entry.is_dir():
            folders.append(entry.name)

#gropuing files according to disease class
for folder in folders:
    classes=pd.read_csv(os.path.join(absulte_path,data_set_path,'Data set 3',folder,'_classes.csv'))
    print(classes.shape)
    #print(classes)
    for row in classes.iterrows():
        #print(row)
        row_data=[]
        #print(row[1]['filename'])
        row_data.append(folder)
        row_data.append(row[1]['filename'])
        if(row[1]['Blister Blight']==1):
            row_data.append('Blister Blight')
        elif(row[1]['Brown Blight']==1):
            row_data.append('Brown Blight')
        elif(row[1]['Gray blight']==1):
            row_data.append('Gray blight')
        elif(row[1]['Healthy']==1):
            row_data.append('Healthy')
        else:
            row_data.append('Red rust')
        #print(row_data)
        data.append(row_data)


#making directories for each disease class in data set 3
disease_names = [
    "Brown Blight (Colletotrichum camelliae)",
    "Blister Blight (Exobasidium vexans)",
    "Gray Blight (Pestalotiopsis theae)",
    "Healthy",
    "Red Rust (Cephaleuros parasiticus)"
]
os.makedirs(os.path.join(absulte_path,data_set_path,"data set 3","reconstructed_dataset"),exist_ok=True)
for disease in disease_names:
    os.makedirs(os.path.join(absulte_path,data_set_path,"data set 3","reconstructed_dataset",disease),exist_ok=True)



#copying and renaming files according to disease class
print("Total files:",len(data))
error_count=0
for file in data:
    file_path=os.path.join(absulte_path,data_set_path,'data set 3',file[0],file[1])
    if not os.path.exists(file_path):
        print("File not found:",file[1])
        error_count+=1
        continue
    match file[2]:
        case "Blister Blight":
            dest_folder="Blister Blight (Exobasidium vexans)"
        case "Brown Blight":
            dest_folder="Brown Blight (Colletotrichum camelliae)"
        case "Gray blight":
            dest_folder="Gray Blight (Pestalotiopsis theae)"
        case "Healthy":
            dest_folder="Healthy"
        case "Red rust":
            dest_folder="Red Rust (Cephaleuros parasiticus)"

    shutil.copy(os.path.join(absulte_path,data_set_path,'data set 3',file[0],file[1]), os.path.join(absulte_path,data_set_path,'data set 3','reconstructed_dataset',dest_folder,file[1]))

print("Total missing files:",error_count)

(299, 6)
(1045, 6)
(150, 6)
Total files: 1494
Total missing files: 0

In [7]:
target_path='data/processed'
data_set_path='data/raw'
dt_count=0
with os.scandir(os.path.join(absulte_path,data_set_path)) as datasets:
    for dataset in datasets:
        data_set_path='data/raw'
        dataset_name=dataset.name
        if dataset.name=='data set 4' or dataset.name=='data set 3' or dataset.name=='data set 6':
            print(dataset_name)
            data_set_path=os.path.join(data_set_path,dataset_name)
            dataset_name='reconstructed_dataset'
        print(dataset_name)
        dt_count+=1
        os.makedirs(os.path.join(absulte_path,target_path,dataset_name), exist_ok=True)
        with os.scandir(os.path.join(absulte_path,data_set_path,dataset_name)) as entries:
            for entry in entries:
                print("     "+entry.name)
                if entry.name == 'test' or entry.name == 'train' or entry.name == 'valid':
                    continue
                if entry.is_dir():
                    images = [f for f in os.listdir(os.path.join(absulte_path,data_set_path, dataset_name, entry.name)) if f.lower().endswith(('.jpg'))]
                    os.makedirs(os.path.join(absulte_path,target_path,dataset.name), exist_ok=True)
                    #print(re.sub(r'\s*\(.*?\)', '', entry.name).strip())
                    print(f"        Number of images in {entry.name}: {len(images)}")
                    count=1
                    if entry.name == 'Healthy leaf':
                        file_name = 'Healthy'
                        foler_name=file_name
                    else:
                        file_name = entry.name
                        foler_name=entry.name
                    os.makedirs(os.path.join(absulte_path,target_path,dataset.name,foler_name), exist_ok=True)
                    for img in images:
                        #print(f"{os.path.join(os.getcwd(), entry.name, img)}")
                        if "- Copy" in img:
                            #print(f"Skipping duplicate image: {img}")
                            continue
                        new_name = f"{re.sub(r'\s*\(.*?\)', '', file_name).strip().replace(' ', '_')}_dt{dt_count}_{count:05d}.jpg"
                        count+=1
                        #print(f"New name: {new_name}")
                        shutil.copy(os.path.join(absulte_path,data_set_path, dataset_name, entry.name, img), os.path.join(absulte_path,target_path,dataset.name,foler_name, new_name))
        print("-"*100)
print("Done")

data set 1 (Vishara uncle's)
     Brown Blight (Colletotrichum camelliae)
        Number of images in Brown Blight (Colletotrichum camelliae): 506
     Gray Blight (Pestalotiopsis theae)
        Number of images in Gray Blight (Pestalotiopsis theae): 1013
     Green mirid bug (Apolygus lucorum)
        Number of images in Green mirid bug (Apolygus lucorum): 1282
     Healthy leaf
        Number of images in Healthy leaf: 935
     Helopeltis (Helopeltis theivora)
        Number of images in Helopeltis (Helopeltis theivora): 607
     Red Rust (Cephaleuros parasiticus)
        Number of images in Red Rust (Cephaleuros parasiticus): 418
     Red spider (Oligonychus coffeae)
        Number of images in Red spider (Oligonychus coffeae): 515
----------------------------------------------------------------------------------------------------
data set 2
     Algal Leaf Spot (Cephaleuros parasiticus)
        Number of images in Algal Leaf Spot (Cephaleuros parasiticus): 153
     Bird Eye Spot (Cercospora theae)
        Number of images in Bird Eye Spot (Cercospora theae): 136
     Brown Blight (Colletotrichum camelliae)
        Number of images in Brown Blight (Colletotrichum camelliae): 270
     Gray Blight (Pestalotiopsis theae)
        Number of images in Gray Blight (Pestalotiopsis theae): 124
     Healthy
        Number of images in Healthy: 100
     Red Leaf Spot (Phoma theicola)
        Number of images in Red Leaf Spot (Phoma theicola): 223
     White Spot (Elsinoë leucospila)
        Number of images in White Spot (Elsinoë leucospila): 190
----------------------------------------------------------------------------------------------------
data set 3
reconstructed_dataset
     Blister Blight (Exobasidium vexans)
        Number of images in Blister Blight (Exobasidium vexans): 277
     Brown Blight (Colletotrichum camelliae)
        Number of images in Brown Blight (Colletotrichum camelliae): 300
     Gray Blight (Pestalotiopsis theae)
        Number of images in Gray Blight (Pestalotiopsis theae): 299
     Healthy
        Number of images in Healthy: 315
     Red Rust (Cephaleuros parasiticus)
        Number of images in Red Rust (Cephaleuros parasiticus): 303
----------------------------------------------------------------------------------------------------
data set 4
reconstructed_dataset
     Algal Leaf Spot (Cephaleuros parasiticus)
        Number of images in Algal Leaf Spot (Cephaleuros parasiticus): 1024
     Brown Blight (Colletotrichum camelliae)
        Number of images in Brown Blight (Colletotrichum camelliae): 976
     Gray Blight (Pestalotiopsis theae)
        Number of images in Gray Blight (Pestalotiopsis theae): 1093
     Healthy
        Number of images in Healthy: 1045
     Helopeltis (Helopeltis theivora)
        Number of images in Helopeltis (Helopeltis theivora): 988
     Red Leaf Spot (Phoma theicola)
        Number of images in Red Leaf Spot (Phoma theicola): 1133
     test
     train
     valid
----------------------------------------------------------------------------------------------------
data set 5
     Blister Blight (Exobasidium vexans)
        Number of images in Blister Blight (Exobasidium vexans): 13500
     Brown Blight (Colletotrichum camelliae)
        Number of images in Brown Blight (Colletotrichum camelliae): 13500
     Healthy
        Number of images in Healthy: 12829
     Helopeltis (Helopeltis theivora)
        Number of images in Helopeltis (Helopeltis theivora): 13500
     Red Rust (Cephaleuros parasiticus)
        Number of images in Red Rust (Cephaleuros parasiticus): 13500
     Red spider (Oligonychus coffeae)
        Number of images in Red spider (Oligonychus coffeae): 13500
----------------------------------------------------------------------------------------------------
data set 6
reconstructed_dataset
     Blister Blight (Exobasidium vexans)
        Number of images in Blister Blight (Exobasidium vexans): 1254
----------------------------------------------------------------------------------------------------
Done

In [8]:
os.rmdir(os.path.join(absulte_path,'data/processed','reconstructed_dataset'))

In [9]:
data_set_path='data/processed'
os.makedirs(os.path.join(absulte_path,'data/processed','final_dataset'), exist_ok=True)
disease_images_count=[]
print(os.path.join(absulte_path,data_set_path))
with os.scandir(os.path.join(absulte_path,data_set_path)) as datasets:
    for dataset in datasets:
        if dataset.name == 'final_dataset':
            continue
        #print(dataset.name)
        with os.scandir(os.path.join(absulte_path,data_set_path, dataset.name)) as entries:
            for entry in entries:
                #print(f"    {entry.name}")
                for i in range(len(disease_images_count)):
                    #print(disease_images_count[i][0])
                    #print(entry.name)
                    if entry.name == disease_images_count[i][0]:
                        images=[f for f in os.listdir(os.path.join(absulte_path,data_set_path, dataset.name,entry.name)) if f.lower().endswith(('.jpg'))]
                        disease_images_count[i][1]+=len(images)
                        for image in images:
                            shutil.copy(os.path.join(absulte_path,data_set_path, dataset.name, entry.name, image),
                                        os.path.join(absulte_path,data_set_path,'final_dataset',entry.name,image))
                        break
                else:
                    images=[f for f in os.listdir(os.path.join(absulte_path,data_set_path, dataset.name,entry.name)) if f.lower().endswith(('.jpg'))]
                    disease_images_count.append([entry.name,len(images)])
                    os.makedirs(os.path.join(absulte_path,'data/processed','final_dataset',entry.name), exist_ok=True)
                    for image in images:
                            shutil.copy(os.path.join(absulte_path,data_set_path, dataset.name, entry.name, image),
                                        os.path.join(absulte_path,'data/processed','final_dataset',entry.name,image))

pd.DataFrame(disease_images_count,columns=['Disease','Number of images'])

e:\DSGP\data/processed

                                      Disease  Number of images
0     Brown Blight (Colletotrichum camelliae)             15495
1          Gray Blight (Pestalotiopsis theae)              2503
2          Green mirid bug (Apolygus lucorum)              1282
3                                     Healthy             15198
4            Helopeltis (Helopeltis theivora)             15095
5          Red Rust (Cephaleuros parasiticus)             14221
6            Red spider (Oligonychus coffeae)             14015
7   Algal Leaf Spot (Cephaleuros parasiticus)              1137
8            Bird Eye Spot (Cercospora theae)               100
9              Red Leaf Spot (Phoma theicola)              1276
10            White Spot (Elsinoë leucospila)               142
11        Blister Blight (Exobasidium vexans)             15031

In [12]:
final_disease_list=['Healthy','Blister Blight (Exobasidium vexans)','Brown Blight (Colletotrichum camelliae)','Gray Blight (Pestalotiopsis theae)','Helopeltis (Helopeltis theivora)','Red Rust (Cephaleuros parasiticus)','Algal Leaf Spot (Cephaleuros parasiticus)']

In [15]:
for folder in disease_images_count:
    if folder[0] not in final_disease_list:
        print(f"Removing folder: {folder[0]}")
        shutil.rmtree(os.path.join(absulte_path,'data/processed','final_dataset',folder[0]))

Removing folder: Green mirid bug (Apolygus lucorum)
Removing folder: Red spider (Oligonychus coffeae)
Removing folder: Bird Eye Spot (Cercospora theae)
Removing folder: Red Leaf Spot (Phoma theicola)
Removing folder: White Spot (Elsinoë leucospila)

[['Brown Blight (Colletotrichum camelliae)', 15495],
 ['Gray Blight (Pestalotiopsis theae)', 2503],
 ['Green mirid bug (Apolygus lucorum)', 1282],
 ['Healthy', 15198],
 ['Helopeltis (Helopeltis theivora)', 15095],
 ['Red Rust (Cephaleuros parasiticus)', 14221],
 ['Red spider (Oligonychus coffeae)', 14015],
 ['Algal Leaf Spot (Cephaleuros parasiticus)', 1137],
 ['Bird Eye Spot (Cercospora theae)', 100],
 ['Red Leaf Spot (Phoma theicola)', 1276],
 ['White Spot (Elsinoë leucospila)', 142],
 ['Blister Blight (Exobasidium vexans)', 15031]]

In [ ]:
data_set_path='data/processed'
dataset_name='final_dataset'
images = [f for f in os.listdir(os.path.join(absulte_path,data_set_path, dataset_name, "Algal Leaf Spot (Cephaleuros parasiticus)")) if f.lower().endswith(('.jpg'))]
for image in images:
    shutil.move(os.path.join(absulte_path,data_set_path, dataset_name, "Algal Leaf Spot (Cephaleuros parasiticus)", image),os.path.join(absulte_path,data_set_path, dataset_name, "Red Rust (Cephaleuros parasiticus)", image))
os.rmdir(os.path.join(absulte_path,data_set_path, dataset_name, "Algal Leaf Spot (Cephaleuros parasiticus)"))

In [22]:
with os.scandir(os.path.join(absulte_path,data_set_path, dataset_name)) as entries:
    for entry in entries:
        if entry.is_dir():
            images = [f for f in os.listdir(os.path.join(absulte_path,data_set_path, dataset_name, entry.name)) if f.lower().endswith(('.jpg'))]
            disease_images_count.append([entry.name,len(images)])
pd.DataFrame(disease_images_count,columns=['Disease','Number of images'])

                                    Disease  Number of images
0       Blister Blight (Exobasidium vexans)             15031
1   Brown Blight (Colletotrichum camelliae)             15495
2        Gray Blight (Pestalotiopsis theae)              2503
3                                   Healthy             15198
4          Helopeltis (Helopeltis theivora)             15095
5        Red Rust (Cephaleuros parasiticus)             15358
6       Blister Blight (Exobasidium vexans)             15031
7   Brown Blight (Colletotrichum camelliae)             15495
8        Gray Blight (Pestalotiopsis theae)              2503
9                                   Healthy             15198
10         Helopeltis (Helopeltis theivora)             15095
11       Red Rust (Cephaleuros parasiticus)             15358